openapi: 3.1.0
info:
  title: Ludownloader backend API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
paths:
  /api/v1/httpdownload:
    post:
      operationId: createDownload
      summary: Create a new download
      responses:
        '200':
          description: Download created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadData'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDownload'
  /api/v1/httpdownload/{id}:
    get:
      operationId: getDownload
      summary: Get data about a download
      responses:
        '200':
          description: Download data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DownloadData'
components:
  schemas:
    DownloadState:
      oneOf:
        - type: object
          title: Complete
          additionalProperties: false
        - type: object
          title: Paused
          properties:
            bytesDownloaded:
              type: integer
              minimum: 0
          required:
            - bytesDownloaded
        - type: object
          title: Running
          properties:
            bytesDownloaded:
              type: integer
              minimum: 0
            bytesPerSecond:
              type: integer
              minimum: 0
          required:
            - bytesPerSecond
            - bytesDownloaded
        - type: object
          title: Error
          properties:
            error:
              type: string
          required:
            - error

    CreateDownload:
      type: object
      properties:
        url:
          type: string
        file_path:
          type: string
      required:
        - url

    DownloadData:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/DownloadMetadata'
        state:
          $ref: '#/components/schemas/DownloadState'
      required:
        - state
        - metadata

    DownloadMetadata:
      type: object
      properties:
        id:
          type: string
          format: uuid
        url:
          type: string
        file_path:
          type: string
        content_length:
          type: integer
          minimum: 0

      required:
        - id
        - url
        - file_path
        - content_length
    
  
