name: Rust

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Downloader
      working-directory: ./downloader
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./downloader
      run: cargo test --verbose
