name: Tauri

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: sudo apt install libdbus-1-dev pkg-config
    - name: Build Tauri App
      working-directory: ./app
      run: |
        yarn install
        yarn tauri build
