name: Tauri

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install Tauri dependencies
      run: |
        sudo apt install libdbus-1-dev pkg-config
        sudo apt install libwebkit2gtk-4.0-dev
        sudo apt install build-essential
        sudo apt install curl
        sudo apt install wget
        sudo apt install libssl-dev
        sudo apt install libgtk-3-dev
        sudo apt install libayatana-appindicator3-dev
        sudo apt install librsvg2-dev
    - name: Build Tauri App
      working-directory: ./app
      run: |
        yarn install
        yarn tauri build
